discord_link: discord.gg/srSSSgJ

storage:
  mysql:
    host: localhost
    port: 3306
    database: botboi
    username: root
    password: password
    table: botboi_keys
    luckperms:
      database: luckperms
      playertable: luckperms_players
      permtable: luckperms_user_permissions
      grouppermtable: luckperms_group_permissions